//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.19 at 12:45:19 PM CEST 
//


package no.uis.service.fsimport.util;

import javax.xml.bind.annotation.adapters.XmlAdapter;

import no.uis.service.studinfo.data.FsSemester;

public class FsSemesterAdapter
    extends XmlAdapter<String, FsSemester>
{

  @Override
  public FsSemester unmarshal(String v) throws Exception {
    return FsSemester.stringToUisSemester(v);
  }

  @Override
  public String marshal(FsSemester v) throws Exception {
    return v.toString();
  }


}
